name: Continuous Development Pipeline

on: pull_request

jobs:
  type-checking:
    name: Type Checking

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          installer-url: https://repo.anaconda.com/miniconda/Miniconda3-py38_4.11.0-Linux-x86_64.sh
          environment-file: environment.yml

      - name: Install package
        shell: bash -l {0}
        run: |
          conda activate test
          python setup.py develop

      - name: Check types with mypy
        shell: bash -l {0}
        run: |
          conda activate test
          mypy --ignore-missing-imports mlp/

  unit-tests:
    name: Unit Tests

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          installer-url: https://repo.anaconda.com/miniconda/Miniconda3-py38_4.11.0-Linux-x86_64.sh
          environment-file: environment.yml

      - name: Install package
        shell: bash -l {0}
        run: |
          conda activate test
          python setup.py develop

      - name: Test with pytest
        shell: bash -l {0}
        run: |
          conda activate test
          pytest --cache-clear --cov=mlp/ tests/ > pytest-coverage.txt

      - name: Comment coverage in PR
        uses: coroo/pytest-coverage-commentator@v1.0.2
