name: Continuous Development Pipeline

on: pull_request

jobs:
  unit-tests:
    name: Unit Tests

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          installer-url: https://repo.anaconda.com/miniconda/Miniconda3-py38_4.11.0-Linux-x86_64.sh
          activate-enironment: mlp
          environment-file: environment.yml
          auto-activate-base: false

      - name: Print conda info
        shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: Install package
        shell: bash -l {0}
        run: |
          conda activate mlp
          python setup.py develop

      - name: Test with pytest
        shell: bash -l {0}
        run: |
          conda activate mlp
          pytest --cache-clear --cov=mlp/ tests/ > pytest-coverage.txt

      - name: Comment coverage in PR
        uses: coroo/pytest-coverage-commentator@v1.0.2
